#!/bin/bash

# exit on any failure
set -e

url_ignore=""
if [ -z "$1" ]; then
    echo "[$(date)] WARNING: no branch name provided for documentation test"
else
    echo "[$(date)] Testing documentation for '$1'"
    if [[ "$1" == release_* ]]; then
        n=${1#*_}
        echo "[$(date)] WARNING: download URLs including version ${n} will be ignored (release branch)";
        ## in case of the release branch, ignore the
        url_ignore="--url-ignore https://github.com/magicDGS/ReadTools/archive/${n}.tar.gz,https://github.com/magicDGS/ReadTools/releases/download/${n}/ReadTools.jar"
        echo "DEBUG: $url_ignore"
    fi
fi

current_dir=${PWD}

cd $(dirname $0)/../docs

# clean the docs
echo -e "[$(date)] Building a clean jekyll site\n"
bundle exec jekyll clean
# building the site with jekyll
bundle exec jekyll build

echo -e "\n[$(date) Executing HTML-proofer\n"
# execute htmlproofer for the sit with the following options
# - Only throw for 400 to 499 http status
# - Allow hash reference (used in menus)
# - Check for our favicon
# - Ignore javadoc - it is not part of the documentation generated by us, but by the javadoc task
# - Check HTML format with Nokogiri
bundle exec -- htmlproofer ${url_ignore} --only-4xx --allow-hash-href --check-favicon --file-ignore /javadoc/ --check_html ./_site

cd $current_dir