#!/bin/bash

# exit on any failure
set -e

current_dir=${PWD}

cd $(dirname $0)/../docs

# clean the docs
echo -e "[$(date)] Building a clean jekyll site\n"
bundle exec jekyll clean
# building the site with jekyll
bundle exec jekyll build

echo -e "\n[$(date) Executing HTML-proofer\n"
# execute htmlproofer for the sit with the following options
# - Allow hash reference as a common practice in jekyll
# - Check for our favicon
# - Ignore javadoc - it is not part of the documentation generated by us, but by the javadoc tasl
bundle exec -- htmlproofer --allow-hash-href --check-favicon --file-ignore /javadoc/ ./_site

cd $current_dir