## TODO: remove this or change
repository: tomjohnson1492/documentation-theme-jekyll

# this property is useful for conditional filtering of content that is separate from the PDF.
output: web

# this appears on the top navigation bar next to the home button
topnav_title: Home

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: ReadTools documentation

# this appears in the footer
company_name: Daniel Gómez-Sánchez
company_logo: false

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
github_editme_path:

# if you're using disqus for comments, add the shortname here. if not, leave this value blank.
disqus_shortname:

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .gitignore
  - /javadoc

# used as a contact email for the Feedback link in the top navigation bar
feedback_subject_line: ReadTools Feedback
feedback_email: daniel.gomez.sanchez@hotmail.es

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# collections are declared here, allowing iteration over them
## renders the content in _tools and processes it, outputing the files
collections:
  tools:
    output: true

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tools"
    values:
      layout: "page"
      comments: false
      search: true
      ## TODO: change for a tool sidebar?
      sidebar: home_sidebar

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      search: true
      sidebar: home_sidebar

## TODO: change!!
sidebars:
- home_sidebar
- mydoc_sidebar

# the description is used in the feed.xml file
## TODO: more descriptive!!
description: "Documentation page for ReaddTools"

# needed for  file only
url: http://magicDGS.github.io/ReadTools
